### ISSUE TITLE
wrong-type-argument consp nil

### ISSUE THREAD

**Issue by voobscout** [jtatarik/magit-gitflow#1]
**Arch Linux** _kernel version 3.18.6-1-ARCH_
**GNU Emacs 24.4.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.14.7) of 2015-01-17 on bisson**
**magit-1.2.0-752-g0bb8e79**
**git version 2.3.0**
**git-flow version 0.4.1**

``` emacs
(require 'magit-gitflow)
```

produces:

Debugger entered--Lisp error: (wrong-type-argument consp nil)
  setcdr(nil (("=u" "Signing key" "--signingkey=" read-file-name)))
  (if (cdr things) (if (magit-key-mode-key-defined-p for-group key) (error "%s is already defined in the %s group." key for-group) (setcdr (cdr things) (cons args (cddr things)))) (setcdr things (list args)))
  (let\* ((options (magit-key-mode-options-for-group for-group)) (things (assoc thing options)) (key (car args))) (if (cdr things) (if (magit-key-mode-key-defined-p for-group key) (error "%s is already defined in the %s group." key for-group) (setcdr (cdr things) (cons args (cddr things)))) (setcdr things (list args))) (setq magit-key-mode-keymaps nil) things)
  magit-key-mode-update-group(gitflow-release-finish arguments "=u" "Signing key" "--signingkey=" read-file-name)
  magit-key-mode-insert-argument(gitflow-release-finish "=u" "Signing key" "--signingkey=" read-file-name)
  apply(magit-key-mode-insert-argument gitflow-release-finish ("=u" "Signing key" "--signingkey=" read-file-name))
  #[385 "\300\301#\207" [apply magit-key-mode-insert-argument] 6 "\n\n(fn &rest ARGS)"](gitflow-release-finish "=u" "Signing key" "--signingkey=" read-file-name)
  byte-code("\300\301\302\303\304\305\306\307!\310\"\311\312%\313!\210\314\315\316$\210\317\320\321$\210\322\323\324$\210\325\326\327$\210\330\331\332$\210\333\334\335$\210\336\337\340$\210\341!\266\342\343\344\303\304\305\306\307!\345\"\311\312%\313!\210\330\346\347$\210\350\351\352$\210\341!\266\353\354\355\303\304\305\306\307!\356\"\311\312%\313!\210\317\357\360$\210\350\351\352$\210\361\362\363$\210\364\365\366$\210\367\370\371$\210\372\373\374$\210\375\376\377$\210\201@

any help would be appreciated!

**Comment by jtatarik** [comment]
magit-1.2.0 - I think this is quite an old release by now. What happens when you try to install magit from MELPA, as described here

https://github.com/magit/magit#installation

**Comment by voobscout** [comment]
got this version from MELPA - http://melpa.org/#/magit
exactly the same error message.

**Comment by jtatarik** [comment]
After loading the melpa magit, what does `M-x magit-version` say? Could it be there are two magit versions installed at the same time, and the older one gets loaded? Can you try from vanilla configuration (`emacs -Q`, then follow the installation steps)?

**Comment by voobscout** [comment]
Indeed, you were right! Another version gets loaded before the latest one from melpa.
Thank you!
