### ISSUE TITLE
Change keybinding for magit-gitflow-popup

### ISSUE THREAD

**Issue by d12frosted** [jtatarik/magit-gitflow#11]
Currently it's bound to `C-f` by default. I propose to change the default to something else, since it's a motion key. And whenever I navigate in magit status buffer I end up opening gitflow popup. 

I am not sure what's the best key binding would be for that, that's why I am opening issue :) 

Best regards.

**Comment by jtatarik** [comment]
I just pushed a fix for this - you can pick your own key by setting the `magit-gitflow-popup-key` variable.

**Comment by d12frosted** [comment]
Nice, thank you
