### ISSUE TITLE
(require 'magit-process)

### ISSUE THREAD

**Issue by xianghx** [jtatarik/magit-gitflow#13]
(require 'magit-process) didn't work. where to find it ?

**Comment by jtatarik** [comment]
In the magit package. Magit must be installed for magit-gitflow to work.

**Comment by xianghx** [comment]
oh,my god . elpa magit have another version. thank you.

Can you add this:
;;;###autoload
(defun turn-on-magit-gitflow ()

**Comment by jtatarik** [comment]
Fixed.
