### ISSUE TITLE
getopt: unrecognized option

### ISSUE THREAD

**Issue by panaak** [jtatarik/magit-gitflow#2]
hi there,

whenever i try to finish a feature/hotfix/release i get a getopt error:

  1 git --no-pager -c core.preloadindex=true flow --cleanup=strip --file=.git/COMMIT_EDITMSG hotfix finish fix-html
flags:WARN getopt: unrecognized option '--cleanup=strip'
getopt: unrecognized option '--file=.git/COMMIT_EDITMSG'
 -- 'hotfix' 'finish' 'fix-html'
flags:FATAL unable to parse provided options with getopt.

am i doing something wrong?

the cli works fine:
`git flow hotfix finish fix-html` output:

Summary of actions:
- Latest objects have been fetched from 'origin'
- Hotfix branch has been merged into 'blisty-dev'
- The hotfix was tagged 'fix-html'
- Hotfix branch has been back-merged into 'develop'
- Hotfix branch 'hotfix/fix-html' has been deleted

emacs: 24.4.1
git: 1.9.3 (Apple Git-50)
magit: 20150124.930
magit-gitflow: 20140512.1437

-mp-

**Comment by jtatarik** [comment]
Interesting. I have tested with the current magit/master and magit-gitflow/master, and my git command line looks like this 

  `git --no-pager -c core.preloadindex=true flow hotfix finish test-hotfix`

None of the unrecognized options (cleanup, file) are present, so it works just fine. The cleanup/file opts are being added by `magit-commit-internal`, but I at this moment I have no idea why this happens for you and not for me. I will investigate some more.

**Comment by jtatarik** [comment]
Found it. Looks like magit cannot locate emacsclient on your machine.

https://github.com/magit/magit/wiki/Emacsclient

Maybe the solution described at http://stackoverflow.com/questions/18856047/emacs-magit-commit-opens-new-emacs-client applies in your situation, too.

**Comment by panaak** [comment]
yes, this did the trick:

(set-variable 'magit-emacsclient-executable "/Applications/Emacs.app/Contents/MacOS/bin/emacsclient")

thanx!
