### ISSUE TITLE
Doesn't work witg magit 2.1

### ISSUE THREAD

**Issue by mattiasb** [jtatarik/magit-gitflow#3]
If I add the following to my `init.el`:

``` lisp
(add-hook 'magit-mode-hook
          (lambda ()
            (require 'magit-gitflow)
            (when (fboundp 'turn-on-magit-gitflow)
              (turn-on-magit-gitflow))))
```

...I get this when starting magit:

```
byte-code: Symbol's function definition is void: magit-key-mode-add-group
```

**Comment by jtatarik** [comment]
You might want to try again, now that magit-gitflow/next has been merged to master.

**Comment by mattiasb** [comment]
And everything works great again! :)

Sweet!

**Comment by kimicla** [comment]
I just add the following to my `init.el`:

```
(add-hook 'magit-mode-hook 'turn-on-magit-gitflow)
```

I run `M-x magit-version` shows:

```
Magit 2.7.0, Git 2.4.9 (Apple Git-60), Emacs 24.5.1, darwin
```

But I get this when I go to magit status:

```
Turning on magit-auto-revert-mode...done
run-hooks: Symbol's function definition is void: turn-on-magit-gitflow
```

How can I fix this, thanks.

**Comment by jtatarik** [comment]
The `turn-on-magit-gitflow` function is provided by the `magit-gitflow` module.

``` lisp
(require 'magit-gitflow)
(add-hook 'magit-mode-hook 'turn-on-magit-gitflow)
```

**Comment by kimicla** [comment]
Yes,  I have installed `magit-gitflow` package.

**Comment by kimicla** [comment]
I can find it in my elpa folder:

```
➜  elpa git:(master) ✗ ll | grep magit
drwxr-xr-x  56 Liebe444ever  staff   1.9K May 26 18:23 magit-2.7.0
drwx------   8 Liebe444ever  staff   272B May 30 16:04 magit-gitflow-2.0.2
drwxr-xr-x   8 Liebe444ever  staff   272B May 26 18:22 magit-popup-2.7.0
```

**Comment by jtatarik** [comment]
It also needs to be loaded. That's what the `(require 'magit-gitflow)` statement does.

The `run-hooks: Symbol's function definition is void: turn-on-magit-gitflow` error message suggests the `magit-gitflow` module has not been loaded for some reason.

**Comment by kimicla** [comment]
I just delete elpa folder and try again with my `init.el` file:

```
(require-package 'magit)
(require-package 'magit-gitflow)
(add-hook 'magit-mode-hook 'turn-on-magit-gitflow)
```

`require-package` is a wrapper, just same meaning to install from melpa.

While I open `magit status`, I got the same error message. And I try `M-x`, and then no `turn-on-magit-gitflow` can be executed.

**Comment by jtatarik** [comment]
What happens when you try to load the library manually? `M-x load-library` `magit-gitflow`

**Comment by kimicla** [comment]
Wow, It works, why do I need to load by this command.

I install other packages only by add `require` in `init.el`.

Thanks any way.
