### ISSUE TITLE
Can't work with magit 2.1.0

### ISSUE THREAD

**Issue by Superbil** [jtatarik/magit-gitflow#4]
`magit-define-popup` have been removed at magit 2.1.0.

**Comment by jtatarik** [comment]
I don't think so. Are you sure you have installed the latest magit-gitflow with magit-2.1.0?

**Comment by Superbil** [comment]
Yes, I install magit-gitflow 20150702.20 and magit-2.1.0. After eval `(require 'magit-gitflow)` that will got error.

```
 Symbol's value as variable is void: magit-gitflow-popup
```

**Comment by jtatarik** [comment]
This sounds strange. Can you double-check you have the latest magit/magit-gitflow, and that there are no older versions laying around, that might get loaded by mistake?

**Comment by Superbil** [comment]
I use the laster magit/magit-gitlfow, I found that maybe the cache `.elc` problem.

It's work! After I re-compiling all packages.

Thank for you help.
