### ISSUE TITLE
'flow' is not a git command. See 'git --help'. ...

### ISSUE THREAD

**Issue by stig** [jtatarik/magit-gitflow#5]
I'm getting this error when attempting to use this module:

```
'flow' is not a git command. See 'git --help'. ...
```

I mean, it _seems_ to work fine and the menu system is taking me through the motions, but once I've typed the name of the feature and hit Enter I get the above error.

I use: `Magit 20150701.1326, Git 2.4.5, Emacs 24.5.1`

**Comment by jtatarik** [comment]
Do you have gitflow installed? https://github.com/petervanderdoes/gitflow

**Comment by jtatarik** [comment]
Month and a half of inactivity, closing.

**Comment by stig** [comment]
Sorry, I missed that you asked a question! I have git flow installed via Homebrew into /usr/local/bin/git-flow -- although I'm using the default /usr/bin/git that comes with OS X Yosemite. Perhaps this is the problem? I'll do some further testing and open a new issue if this turns out not to be it.

**Comment by rdgreen** [comment]
That is the cause of this problem, yes. There is an entry in the magit FAQ that shows how to fix this - or you can just start emacs from the terminal.
