### ISSUE TITLE
Does not work with new release of magit

### ISSUE THREAD

**Issue by greenrd** [jtatarik/magit-gitflow#6]
I get:

`Debugger entered--Lisp error: (void-variable magit-gitflow-popup)`

**Comment by jtatarik** [comment]
This sounds like old magit (1.4) version getting loaded - clean your system of old magit .el or .elc files.

**Comment by greenrd** [comment]
Not sure what happened there, but reinstalling magit-gitflow fixed it. I thought I'd already tried that though.
