### ISSUE TITLE
Messages from magit hide error message from magit-gitflow

### ISSUE THREAD

**Issue by greenrd** [jtatarik/magit-gitflow#8]
As a result, there is no clear indication that anything is wrong if a feature branch creation fails (except that the branch remains the same in the magit status buffer)

The minibuffer just shows:

(No buffers need to be reverted)

after the operation has failed.

This may be a fundamental design problem in... something, I'm not sure what. I have a feeling that the combination of emacs minibuffer + async + async error reporting = really bad idea, for exactly this kind of reason.

**Comment by jtatarik** [comment]
How can I reproduce it? I tried to create an already existing feature branch, and got an error message in minibuffer.

**Comment by greenrd** [comment]
You need to use the latest version of magit.

**Comment by jtatarik** [comment]
I have magit-20150824 and I still get a nice minibuffer error message. Can you provide a step-by-step scenario for me to reproduce?

**Comment by greenrd** [comment]
Try to create a feature branch in a repository which git-flow has not been initialised in. You may have some magit options customised which are preventing you from seeing this. Try commenting out your magit options in .emacs and restarting emacs.

Well, I do get an error message, but it is quickly replaced by the "no buffers need to be reverted" message, which stays around for much longer.

**Comment by jtatarik** [comment]
My only idea at this moment is

```
(setq magit-revert-buffers 'silent)
```

**Comment by jtatarik** [comment]
This should not be an issue with the latest magit anymore.
